import React from 'react'
import PropTypes from 'prop-types'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

RootLayout.propTypes = {
  children: PropTypes.object.isRequired
}

export default function RootLayout ({ children }) {
  return (<>{children}</>)
}
